CREATE TABLE TB_AUTORES(
SEQAUTORES      INTEGER,
NOME            VARCHAR2(60),
CONSTRAINT pk_tb_autores_seqautores PRIMARY KEY (SEQAUTORES)
);

-- USE AS PRIMARY KEY
CREATE SEQUENCE SEQAUTORES
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
CACHE 20;


