CREATE OR REPLACE PROCEDURE pincluirbibliotecaria
(p_SEQBIBLIOTECARIA IN TB_BIBLIOTECARIAS.SEQBIBLIOTECARIA%type, p_NOME IN TB_BIBLIOTECARIAS.NOME%type,
p_RG IN TB_BIBLIOTECARIAS.RG%type, p_CPF IN TB_BIBLIOTECARIAS.CPF%type, p_SALARIO IN TB_BIBLIOTECARIAS.SALARIO%type,
p_STATUS IN TB_BIBLIOTECARIAS.STATUS%type)
IS
BEGIN
    INSERT INTO TB_BIBLIOTECARIAS (SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
    VALUES (
    p_SEQBIBLIOTECARIA,
    p_NOME,
    p_RG,
    p_CPF,
    P_SALARIO,
    p_STATUS
    );
    COMMIT;
END;

EXECUTE pincluirbiliotecaria(SEQBIBLIOTECARIA.nextval, 'JÚLIA DIAS', 859874521, 63598742510, 900, 'ES');

INSERT INTO tb_bibliotecarias (SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
VALUES (
SEQBIBLIOTECARIA.NEXTVAL,
'DEBORA ALMEIDA',
345368712,
25698489670,
1750,
'EF'
);

INSERT INTO tb_bibliotecarias (SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
VALUES (
SEQBIBLIOTECARIA.NEXTVAL,
'VITORIA ALONSO',
564258756,
36547895152,
1750,
'ES'
);

INSERT INTO tb_bibliotecarias (SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
VALUES (
SEQBIBLIOTECARIA.NEXTVAL,
'CRISTINA SOUSA',
458742569,
25489657158,
1750,
'EF'
);

UPDATE TB_BIBLIOTECARIAS
SET SALARIO = 900
WHERE SEQBIBLIOTECARIA = 2;

/*
CREATE OR REPLACE TRIGGER aitg_efetestag
AFTER INSERT ON TB_BIBLIOTECARIAS
DECLARE v_status TB_BIBLIOTECARIAS.STATUS%type;
BEGIN
    SELECT STATUS 
    INTO v_status
    FROM TB_BIBLIOTECARIAS;
    
    IF v_status = 'ES' THEN
        DELETE FROM TB_ESTAGIO;
        
        INSERT INTO TB_ESTAGIO(SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
        SELECT * 
        FROM TB_BIBLIOTECARIAS;
        
    ELSIF v_status = 'EF' THEN
        DELETE FROM TB_EFETIVADO;
        
        INSERT INTO TB_EFETIVADO(SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
        SELECT * 
        FROM TB_BIBLIOTECARIAS;
    END IF;
END;
*/