CREATE TABLE TB_BIBLIOTECARIAS(
SEQBIBLIOTECARIA    INTEGER,
NOME                VARCHAR2(60),
RG                  NUMBER,
CPF                 NUMBER,
SALARIO             NUMBER,
CONSTRAINT pk_tb_bibliotecarias_seqbibliotecaria PRIMARY KEY (SEQBIBLIOTECARIA)
);

CREATE SEQUENCE SEQBIBLIOTECARIA
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
CACHE 20;

INSERT INTO tb_bibliotecarias (SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO)
VALUES (
SEQBIBLIOTECARIA.NEXTVAL,
'DÉBORA ALMEIDA',
345368712,
25698489670,
1750
);

INSERT INTO tb_bibliotecarias (SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
VALUES (
SEQBIBLIOTECARIA.NEXTVAL,
'VITOR ALONSO',
564258756,
36547895152,
1750,
'ES'
);

SELECT * FROM tb_bibliotecarias;

UPDATE TB_BIBLIOTECARIAS
SET SALARIO = 900
WHERE SEQBIBLIOTECARIA = 2;

ALTER TABLE TB_BIBLIOTECARIAS
MODIFY (SEQBIBLIOTECARIA NOT NULL);

ALTER TABLE TB_BIBLIOTECARIAS
ADD STATUS VARCHAR(2);

UPDATE TB_BIBLIOTECARIAS
SET STATUS = 'EF'
WHERE SEQBIBLIOTECARIA = 1;