CREATE TABLE TB_CATEGORIAS(
SEQCATEGORIA    INTEGER,
DESCRICAO       VARCHAR2(144),
CONSTRAINT pk_tb_categorias_seqcategoria PRIMARY KEY (SEQCATEGORIA)
);

CREATE SEQUENCE SEQCATEGORIA
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
CACHE 20;