CREATE TABLE TB_CLIENTES(
SEQCLIENTE  INTEGER NOT NULL,
NOME        VARCHAR2(60),
ENDERECO    VARCHAR2(100),
TELEFONE    NUMBER,
CONSTRAINT pk_tb_clientes_seqcliente PRIMARY KEY (SEQCLIENTE)
);

CREATE SEQUENCE SEQCLIENTE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
CACHE 20;