CREATE TABLE TB_EDITORAS (
SEQEDITORA  INTEGER NOT NULL,
ENDERECO    VARCHAR2(200),
NOME        VARCHAR2(60),
CONSTRAINT pk_tb_editoras_id PRIMARY KEY (SEQEDITORA)
);

-- USE AS PRIMARY KEY
CREATE SEQUENCE SEQEDITORA
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
CACHE 20;

-- INSERTIONS
INSERT INTO tb_editoras(SEQEDITORA, ENDERECO, NOME)
VALUES (
    SEQEDITORA.NEXTVAL,
    UPPER('Av. Pres. Kennedy, 1500 - Ribeirânia, Ribeirão Preto - SP'),
    UPPER('Saraiva')
);

INSERT INTO tb_editoras(SEQEDITORA, ENDERECO, NOME)
VALUES (
    SEQEDITORA.NEXTVAL,
    UPPER('Alameda Caiapós, 425 - Centro Empresarial Tamboré, Barueri - SP'),
    UPPER('Panini')
);

INSERT INTO tb_editoras(SEQEDITORA, ENDERECO, NOME)
VALUES (
    SEQEDITORA.NEXTVAL,
    UPPER('R. da Quitanda, 86 - Centro, Rio de Janeiro - RJ'),
    UPPER('HarperCollins')
);

INSERT INTO tb_editoras(SEQEDITORA, ENDERECO, NOME)
VALUES (
    SEQEDITORA.NEXTVAL,
    UPPER('Rua Tabapuã, 81 - Itaim Bibi, São Paulo - SP'),
    UPPER('Editora Aleph')
);

INSERT INTO tb_editoras(SEQEDITORA, ENDERECO, NOME)
VALUES (
    SEQEDITORA.NEXTVAL,
    UPPER('R. Viúva Cláudio, 291 - Jacaré, Rio de Janeiro - RJ'),
    UPPER('Alta Books')
);

SELECT * FROM TB_EDITORAS;