CREATE TABLE TB_EFETIVADO AS
SELECT * FROM tb_bibliotecarias;

ALTER TABLE TB_EFETIVADO
ADD DTAADMISSAO DATE;

UPDATE TB_EFETIVADO
SET DTAADMISSAO = TO_DATE('03/10/2017', 'DD/MM/YYYY')
WHERE SEQBIBLIOTECARIA = 1;

DELETE FROM TB_EFETIVADO
WHERE SEQBIBLIOTECARIA = 2;

SELECT * FROM TB_EFETIVADO;