CREATE TABLE TB_ESTANTES(
SEQESTANTE  NUMBER,
CORREDOR    NUMBER,
CONSTRAINT pk_tb_estantes_seqestante PRIMARY KEY (SEQESTANTE)
);

CREATE SEQUENCE SEQESTANTE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
CACHE 20;