CREATE TABLE TB_INSTITUICAOENSINO(
SEQINSTENSINO   INTEGER,
NOME            VARCHAR2(100),
CONSTRAINT pk_tb_instituicaoensino_seqinstensino PRIMARY KEY (SEQINSTENSINO)
);

CREATE SEQUENCE SEQINSTENSINO
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
CACHE 20;