-- ISBN MUST BE THE PRIMARY KEY
CREATE TABLE TB_LIVROS(
ISBN        NUMBER,
TITULO      VARCHAR2(100),
VOLUME      INTEGER,
NROPAGINA   NUMBER,
ANO         NUMBER,
CONSTRAINT pk_tb_livros_isbn PRIMARY KEY (ISBN)
);



