-- INCLUDE DATA IN TB_AUTORES
CREATE OR REPLACE PROCEDURE pincautores
(p_SEQAUTORES IN TB_AUTORES.SEQAUTORES%type, p_NOME IN TB_AUTORES.NOME%type)
IS
BEGIN
    INSERT INTO TB_AUTORES(SEQAUTORES, NOME)
    VALUES(
        p_SEQAUTORES,
        p_NOME
    );
    COMMIT;
END;

-- INCLUDE DATA IN TB_BIBLIOTECARIA
CREATE OR REPLACE PROCEDURE pincbibliotecaria
(p_SEQBIBLIOTECARIA IN TB_BIBLIOTECARIAS.SEQBIBLIOTECARIA%type, p_NOME IN TB_BIBLIOTECARIAS.NOME%type,
p_RG IN TB_BIBLIOTECARIAS.RG%type, p_CPF IN TB_BIBLIOTECARIAS.CPF%type, p_SALARIO IN TB_BIBLIOTECARIAS.SALARIO%type,
p_STATUS IN TB_BIBLIOTECARIAS.STATUS%type)
IS
BEGIN
    INSERT INTO TB_BIBLIOTECARIAS (SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
    VALUES (
        p_SEQBIBLIOTECARIA,
        p_NOME,
        p_RG,
        p_CPF,
        P_SALARIO,
        p_STATUS
    );
    COMMIT;
END;

-- INCLUDE DATA IN TB_CATEGORIA
CREATE OR REPLACE PROCEDURE pinccategoria
(p_SEQCATEGORIA IN TB_CATEGORIAS.SEQCATEGORIA%type, p_DESCRICAO IN TB_CATEGORIAS.DESCRICAO%type)
IS
BEGIN
    INSERT INTO TB_CATEGORIAS(SEQCATEGORIA, DESCRICAO)
    VALUES(
        p_SEQCATEGORIA,
        p_DESCRICAO
    );
    COMMIT;
END;

-- INCLUDE DATA IN TB_CLIENTES
CREATE OR REPLACE PROCEDURE pinccliente
(p_SEQCLIENTE IN TB_CLIENTES.SEQCLIENTE%type, p_NOME IN TB_CLIENTES.NOME%type,
p_ENDERECO IN TB_CLIENTES.ENDERECO%type, p_TELEFONE IN TB_CLIENTES.TELEFONE%type)
IS
BEGIN
    INSERT INTO TB_CLIENTES (SEQCLIENTE, NOME, ENDERECO, TELEFONE)
    VALUES (
        p_SEQCLIENTE,
        p_NOME,
        p_ENDERECO,
        p_TELEFONE
    );
    COMMIT;
END;

-- INCLUDE DATA IN TB_EDITORAS
CREATE OR REPLACE PROCEDURE pinceditora
(p_seqeditora IN TB_EDITORAS.SEQEDITORA%type, p_endereco IN TB_EDITORAS.ENDERECO%type,
p_nome IN TB_EDITORAS.NOME%type)
IS
BEGIN
    INSERT INTO tb_editoras(SEQEDITORA, ENDERECO, NOME)
    VALUES (
        p_seqeditora,
        UPPER(p_endereco),
        UPPER(p_nome)
    );
    COMMIT;
END;

-- INCLUDE DATA IN TB_ESTANTES
CREATE OR REPLACE PROCEDURE pincestante
(p_SEQESTANTE IN TB_ESTANTES.SEQESTANTE%type, p_CORREDOR IN TB_ESTANTES.CORREDOR%type)
IS
BEGIN
    INSERT INTO TB_ESTANTES(SEQESTANTE, CORREDOR)
    VALUES(
        p_SEQESTANTE,
        p_CORREDOR
    );
    COMMIT;
END;

-- INCLUDE DATA IN TB_EXEMPLARES
CREATE OR REPLACE PROCEDURE pinceexemplar
(p_SEQEXEMPLARES IN TB_EXEMPLARES.SEQEXEMPLARES%type, p_QNTDE IN TB_EXEMPLARES.QNTDE%type,
p_ESTADO IN TB_EXEMPLARES.ESTADO%type)
IS
BEGIN
    INSERT INTO TB_EXEMPLARES(SEQEXEMPLARES, QNTDE, ESTADO)
    VALUES(
        p_SEQEXEMPLARES,
        p_QNTDE,
        p_ESTADO
    );
    COMMIT;
END;

-- INCLUDE DATA IN TB_INSTITUICAOENSINO
CREATE OR REPLACE PROCEDURE pincinstensino
(p_SEQINSTENSINO IN TB_INSTITUICAOENSINO.SEQINSTENSINO%type, p_NOME IN TB_INSTITUICAOENSINO.NOME%type)
IS
BEGIN
    INSERT INTO TB_INSTITUICAOENSINO(SEQINSTENSINO, NOME)
    VALUES(
        p_SEQINSTENSINO,
        p_NOME
    );
    COMMIT;
END;

-- INCLUDE DATA IN TB_LIVROS
CREATE OR REPLACE PROCEDURE pinclivro
(p_ISBN IN TB_LIVROS.ISBN%type, p_EDITORA IN TB_LIVROS.EDITORA%type,
p_TITULO IN TB_LIVROS.TITULO%type, p_VOLUME IN TB_LIVROS.VOLUME%type,
p_NROPAGINA IN TB_LIVROS.NROPAGINA%type, p_ANO IN TB_LIVROS.ANO%type)
IS
BEGIN
    INSERT INTO TB_LIVROS(ISBN, EDITORA, TITULO, VOLUME, NROPAGINA, ANO)
    VALUES(
        p_ISBN,
        p_EDITORA,
        p_TITULO,
        p_VOLUME,
        p_NROPAGINA,
        p_ANO
    );
    COMMIT;
END;