-- INCLUDE DATA IN TB_BIBLIOTECARIA
CREATE OR REPLACE PROCEDURE pincbibliotecaria
(p_SEQBIBLIOTECARIA IN TB_BIBLIOTECARIAS.SEQBIBLIOTECARIA%type, p_NOME IN TB_BIBLIOTECARIAS.NOME%type,
p_RG IN TB_BIBLIOTECARIAS.RG%type, p_CPF IN TB_BIBLIOTECARIAS.CPF%type, p_SALARIO IN TB_BIBLIOTECARIAS.SALARIO%type,
p_STATUS IN TB_BIBLIOTECARIAS.STATUS%type)
IS
BEGIN
    INSERT INTO TB_BIBLIOTECARIAS (SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
    VALUES (
        p_SEQBIBLIOTECARIA,
        p_NOME,
        p_RG,
        p_CPF,
        P_SALARIO,
        p_STATUS
    );
    COMMIT;
END;

-- INCLUDE DATA IN TB_EDITORAS
CREATE OR REPLACE PROCEDURE pinceditora
(p_seqeditora IN TB_EDITORAS.SEQEDITORA%type, p_endereco IN TB_EDITORAS.ENDERECO%type,
p_nome IN TB_EDITORAS.NOME%type)
IS
BEGIN
    INSERT INTO tb_editoras(SEQEDITORA, ENDERECO, NOME)
    VALUES (
        p_seqeditora,
        UPPER(p_endereco),
        UPPER(p_nome)
    );
    COMMIT;
END;