CREATE TABLE TB_BIBLIOTECARIAS(
SEQBIBLIOTECARIA    INTEGER NOT NULL,
NOME                VARCHAR2(60),
RG                  NUMBER(9),
CPF                 NUMBER(11),
SALARIO             NUMBER,
STATUS              VARCHAR2(2),
CONSTRAINT pk_tb_bibliotecarias_seqbibliotecaria PRIMARY KEY (SEQBIBLIOTECARIA)
);

CREATE TABLE TB_ESTAGIO(
SEQESTAGIO          INTEGER NOT NULL,
SEQBIBLIOTECARIA    INTEGER NOT NULL,
NOME                VARCHAR2(60),
RG                  NUMBER(9),
CPF                 NUMBER(11),
SALARIO             NUMBER,
STATUS              VARCHAR(2),
CONSTRAINT pk_tb_estagio_seqestagio PRIMARY KEY (SEQESTAGIO),
CONSTRAINT fk_tb_estagio_seqbibliotecaria FOREIGN KEY (SEQBIBLIOTECARIA) REFERENCES TB_BIBLIOTECARIAS
);

CREATE TABLE TB_EFETIVO(
SEQEFETIVO          INTEGER NOT NULL,
SEQBIBLIOTECARIA    INTEGER NOT NULL,
NOME                VARCHAR2(60),
DTAADMISSAO         DATE,
RG                  NUMBER(9),
CPF                 NUMBER(11),
SALARIO             NUMBER,
STATUS              VARCHAR(2),
CONSTRAINT pk_tb_efetivo_seqefetivo PRIMARY KEY (SEQEFETIVO),
CONSTRAINT fk_tb_efetivo_seqbibliotecaria FOREIGN KEY (SEQBIBLIOTECARIA) REFERENCES TB_BIBLIOTECARIAS
);

CREATE TABLE TB_AUTORES(
SEQAUTORES      INTEGER,
NOME            VARCHAR2(60),
CONSTRAINT pk_tb_autores_seqautores PRIMARY KEY (SEQAUTORES)
);

CREATE TABLE TB_CATEGORIAS(
SEQCATEGORIA    INTEGER,
DESCRICAO       VARCHAR2(144),
CONSTRAINT pk_tb_categorias_seqcategoria PRIMARY KEY (SEQCATEGORIA)
);

CREATE TABLE TB_CLIENTES(
SEQCLIENTE  INTEGER NOT NULL,
NOME        VARCHAR2(60),
ENDERECO    VARCHAR2(100),
TELEFONE    NUMBER,
CONSTRAINT pk_tb_clientes_seqcliente PRIMARY KEY (SEQCLIENTE)
);

CREATE TABLE TB_EDITORAS (
SEQEDITORA  INTEGER NOT NULL,
ENDERECO    VARCHAR2(200),
NOME        VARCHAR2(60),
CONSTRAINT pk_tb_editoras_id PRIMARY KEY (SEQEDITORA)
);

CREATE TABLE TB_ESTANTES(
SEQESTANTE  NUMBER NOT NULL,
CORREDOR    NUMBER,
CONSTRAINT pk_tb_estantes_seqestante PRIMARY KEY (SEQESTANTE)
);

CREATE TABLE TB_EXEMPLARES(
SEQEXEMPLARES INTEGER NOT NULL,
QNTDE         NUMBER NOT NULL,
ESTADO        VARCHAR2(1),
CONSTRAINT pk_tb_exemplares_seqexemplares PRIMARY KEY (SEQEXEMPLARES)
);

CREATE TABLE TB_INSTITUICAOENSINO(
SEQINSTENSINO   INTEGER,
NOME            VARCHAR2(100),
CONSTRAINT pk_tb_instituicaoensino_seqinstensino PRIMARY KEY (SEQINSTENSINO)
);

CREATE TABLE TB_LIVROS(
ISBN        NUMBER NOT NULL,
EDITORA     INTEGER NOT NULL,
TITULO      VARCHAR2(100),
VOLUME      INTEGER,
NROPAGINA   NUMBER,
ANO         NUMBER,
CONSTRAINT pk_tb_livros_isbn PRIMARY KEY (ISBN),
CONSTRAINT fk_tb_livros_editora FOREIGN KEY (EDITORA) REFERENCES TB_EDITORAS(SEQEDITORA)
);