-- TRIGGER FOR TB_ESTAGIO
CREATE OR REPLACE TRIGGER aiutg_estag
AFTER INSERT OR UPDATE ON TB_BIBLIOTECARIAS
FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'ES' THEN
        INSERT INTO TB_ESTAGIO(SEQESTAGIO, SEQBIBLIOTECARIA, NOME, RG, CPF, SALARIO, STATUS)
        VALUES(
            SEQESTAGIO.NEXTVAL,
            :NEW.SEQBIBLIOTECARIA,
            :NEW.NOME,
            :NEW.RG,
            :NEW.CPF,
            :NEW.SALARIO,
            :NEW.STATUS
        );
    END IF;
END;

-- TRIGGER FOR TB_EFETIVO
CREATE OR REPLACE TRIGGER aiutg_efetv
AFTER INSERT OR UPDATE ON TB_BIBLIOTECARIAS
FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'EF' THEN
        INSERT INTO TB_EFETIVO(SEQEFETIVO, SEQBIBLIOTECARIA, NOME, DTAADMISSAO, RG, CPF, SALARIO, STATUS)
        VALUES(
            SEQEFETIVO.NEXTVAL,
            :NEW.SEQBIBLIOTECARIA,
            :NEW.NOME,
            SYSDATE,
            :NEW.RG,
            :NEW.CPF,
            :NEW.SALARIO,
            :NEW.STATUS
        );
    END IF;
END;